In [1]:
import numpy as np

In [2]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b=np.ones((3,3),dtype='int32')
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [9]:
b[1,1]=9.
b

array([[1, 1, 1],
       [1, 9, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
c=np.random.uniform(3,4,size=(2,3)) 
c

array([[3.99629443, 3.71938114, 3.79151889],
       [3.38134531, 3.44961869, 3.04532475]])

In [22]:
d=np.random.rand(10)  #rand toujours genere des valeurs entre 0 et 1
e=np.random.randint(5,8,10)   #si size 1d ->sans size=
d
e

array([5, 7, 7, 7, 6, 5, 7, 5, 6, 5], dtype=int32)

In [24]:
f=np.random.rand(5,5)
f

array([[0.77288426, 0.77486972, 0.13030537, 0.72519422, 0.34934268],
       [0.9871977 , 0.43871203, 0.36773262, 0.60347323, 0.52667883],
       [0.28840503, 0.42507422, 0.16533099, 0.6982334 , 0.1116395 ],
       [0.39323813, 0.96996486, 0.12533311, 0.23508857, 0.42281689],
       [0.66376378, 0.76011214, 0.47010725, 0.51501136, 0.75042178]])

In [25]:
np.sum(f)

np.float64(12.670931667384014)

In [48]:
np.min(f,axis=0)

array([0.28840503, 0.42507422, 0.12533311, 0.23508857, 0.1116395 ])

In [27]:
np.average(f)

np.float64(0.5068372666953606)

In [28]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr*2
arr**2

array([ 1,  4,  9, 16, 25])

In [ ]:
t=np.arange(0,16,1).reshape(4,4) #arange(start,stop,step)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
tab=np.linspace(0,16,5) #linspace(start,stop,number of elements)
tab

array([ 0.,  4.,  8., 12., 16.])

In [37]:
t[0,:]

array([0, 1, 2, 3])

In [38]:
t[1:-1,1:-1]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
tt=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
tt.reshape(3,4)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack([v1,v2])
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6])

In [ ]:
a1=np.random.randint(1,6,size=(2,2))
a2=np.random.randint(1,6,size=(2,2))
np.matmul(a1,a2)  #ou bien a1@a2

array([[ 7, 10],
       [ 3,  4]], dtype=int32)

In [53]:
np.linalg.det(a1)

np.float64(2.0000000000000004)

In [54]:
np.linalg.inv(a1)

array([[ 0.5, -0.5],
       [-0.5,  1.5]])

In [69]:
notes=np.random.uniform(0,20,size=10)
notes=np.round(notes)
np.size(notes[notes>10])

4

In [70]:
notes>10

array([False, False,  True,  True, False,  True, False, False, False,
        True])

In [71]:
notes[notes>10]

array([15., 15., 16., 20.])

In [ ]:
np.mean(notes) #moyenne
np.var(notes) #variance
np.std(notes) #ecart type

np.float64(9.2)

In [74]:
filedata=np.genfromtxt('text.txt', delimiter=',')
filedata

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
m=np.array([[1,2],[3,4]])
m.T   #transposée

array([[1, 3],
       [2, 4]])